[package]
name = "api"
version = "0.1.0"
authors = ["cmgriffing"]

[dependencies]
nickel = "*"
log = "*"
config = "~0.1.0"
hyper = "0.8.1"
regex = "*"
quick-xml = "*"
serde = "*"
serde_json = "*"
redis = "*"